<a href="https://colab.research.google.com/github/yasashviagarwal01-coder/DSA-Python/blob/main/netflix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
   #NETFLIX PROJECT

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Netflix/Copy of combined_data_1.txt.zip',header=None,names=['Cust_ID','Ratings'],usecols=[0,1])

In [ ]:
df
#data us grouped

          Cust_ID  Ratings
0              1:      NaN
1         1488844      3.0
2          822109      5.0
3          885013      4.0
4           30878      4.0
...           ...      ...
24058258  2591364      2.0
24058259  1791000      2.0
24058260   512536      5.0
24058261   988963      3.0
24058262  1704416      3.0

[24058263 rows x 2 columns]

In [ ]:
#we need to get
#Movie count
#Customers count
#Ratings count
#Stars count

#Bcoz we use this in future

In [ ]:
#Movie count
df.isnull().sum()

Cust_ID       0
Ratings    4499
dtype: int64

In [ ]:
movie_count=df.isnull().sum()['Ratings']
movie_count

np.int64(4499)

In [ ]:
#Customer count(unique)
total_uni=df['Cust_ID'].nunique()
total_uni

475257

In [ ]:
cust_count=total_uni-movie_count
cust_count

np.int64(470758)

In [ ]:
#Ratings count
ratings_count=df['Ratings'].count()-movie_count
ratings_count

np.int64(24049265)

In [ ]:
#Stars count( i wanna k how many 4 stars are there and so on...)
stars_count=df['Ratings'].value_counts()
stars_count

Ratings
4.0    8085741
3.0    6904181
5.0    5506583
2.0    2439073
1.0    1118186
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24058263 entries, 0 to 24058262
Data columns (total 2 columns):
 #   Column   Dtype
---  ------   -----
 0   Cust_ID  object
 1   Ratings  float64
dtypes: float64(1), object(1)
memory usage: 367.1+ MB

In [ ]:
#IMP STEP
movie_id=None
movie_list=[]

for customer in df['Cust_ID']:
  if ":" in customer:
    movie_id=int(customer.replace(":",""))

  movie_list.append(movie_id)

In [ ]:
movie_list

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [ ]:
#Now we add in the dataframe
df['Movie_Id']=movie_list
df

          Cust_ID  Ratings  Movie_Id
0              1:      NaN         1
1         1488844      3.0         1
2          822109      5.0         1
3          885013      4.0         1
4           30878      4.0         1
...           ...      ...       ...
24058258  2591364      2.0      4499
24058259  1791000      2.0      4499
24058260   512536      5.0      4499
24058261   988963      3.0      4499
24058262  1704416      3.0      4499

[24058263 rows x 3 columns]

In [ ]:
#Now here'
#Everything is good the rows with null values are not required.
df.dropna(inplace=True)

In [ ]:
df

          Cust_ID  Ratings  Movie_Id
1         1488844      3.0         1
2          822109      5.0         1
3          885013      4.0         1
4           30878      4.0         1
5          823519      3.0         1
...           ...      ...       ...
24058258  2591364      2.0      4499
24058259  1791000      2.0      4499
24058260   512536      5.0      4499
24058261   988963      3.0      4499
24058262  1704416      3.0      4499

[24053764 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   Cust_ID   object
 1   Ratings   float64
 2   Movie_Id  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [ ]:
#Lets convert obj into int
df['Cust_ID']=df['Cust_ID'].astype('int')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   Cust_ID   int64
 1   Ratings   float64
 2   Movie_Id  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

In [ ]:
#So if give this much data it will take lot of time'
#So we will filter the data ---> But how?
#less no.of ratings ---> drop
#Customers who rateed less movies ---> drop

#But how can we do this?
#percentile

In [ ]:
#so for this i need to get count of rtaings for each movie

movie_rat_count=df['Movie_Id'].value_counts()
movie_rat_count

Movie_Id
1905    193941
2152    162597
3860    160454
4432    156183
571     154832
         ...
4294        44
915         43
3656        42
4338        39
4362        36
Name: count, Length: 4499, dtype: int64

In [ ]:
bench_marks1=round(movie_rat_count.quantile(0.6),0)
bench_marks1


#so now if a movie ratings count having below 908 i gonna drop them

np.float64(908.0)

In [ ]:
drop_movie_index=movie_rat_count[movie_rat_count<bench_marks1].index
drop_movie_index

# so here i got the movie ids that i want to drop

Index([1598, 1647, 1733, 4099, 1616, 1446,  263,  160, 4259,  322,
       ...
       1858, 4035, 3693, 2805,  820, 4294,  915, 3656, 4338, 4362],
      dtype='int64', name='Movie_Id', length=2699)

In [ ]:
#2nd filter
cust_rat_count=df['Cust_ID'].value_counts()
cust_rat_count

Cust_ID
305344     4467
387418     4422
2439493    4195
1664010    4019
2118461    3769
           ...
739382        1
1504246       1
1244849       1
1558754       1
258446        1
Name: count, Length: 470758, dtype: int64

In [ ]:
bench_marks2=round(cust_rat_count.quantile(0.6),0)
bench_marks2

np.float64(36.0)

In [ ]:
drop_cust_index=cust_rat_count[cust_rat_count<bench_marks2].index
drop_cust_index

Index([1804808, 2619850, 1023928, 1475023, 2569169, 1961632, 2548215, 2390820,
       1691756, 2485501,
       ...
         11326,  116898,   68286, 1847608, 1685763,  739382, 1504246, 1244849,
       1558754,  258446],
      dtype='int64', name='Cust_ID', length=282042)

In [ ]:
drop_movie_index,drop_cust_index

(Index([1598, 1647, 1733, 4099, 1616, 1446,  263,  160, 4259,  322,
        ...
        1858, 4035, 3693, 2805,  820, 4294,  915, 3656, 4338, 4362],
       dtype='int64', name='Movie_Id', length=2699),
 Index([1804808, 2619850, 1023928, 1475023, 2569169, 1961632, 2548215, 2390820,
        1691756, 2485501,
        ...
          11326,  116898,   68286, 1847608, 1685763,  739382, 1504246, 1244849,
        1558754,  258446],
       dtype='int64', name='Cust_ID', length=282042))

In [ ]:
df=df[~df['Movie_Id'].isin(drop_movie_index)]
df=df[~df['Cust_ID'].isin(drop_cust_index)]

In [ ]:
df

          Cust_ID  Ratings  Movie_Id
696        712664      5.0         3
697       1331154      4.0         3
698       2632461      3.0         3
699         44937      5.0         3
700        656399      4.0         3
...           ...      ...       ...
24056842  1055714      5.0      4496
24056843  2643029      4.0      4496
24056844   267802      4.0      4496
24056845  1559566      3.0      4496
24056846   293198      3.0      4496

[19695836 rows x 3 columns]

In [ ]:
#cross validation---->

In [ ]:
df

          Cust_ID  Ratings  Movie_Id
696        712664      5.0         3
697       1331154      4.0         3
698       2632461      3.0         3
699         44937      5.0         3
700        656399      4.0         3
...           ...      ...       ...
24056842  1055714      5.0      4496
24056843  2643029      4.0      4496
24056844   267802      4.0      4496
24056845  1559566      3.0      4496
24056846   293198      3.0      4496

[19695836 rows x 3 columns]

In [ ]:
movie_title=pd.read_csv('/content/drive/MyDrive/Netflix/Copy of movie_titles (2).csv',encoding='ISO-8859-1',header=None,names=['Movie_ID','Year','Name'],usecols=[0,1,2])

In [ ]:
movie_title

       Movie_ID    Year                                               Name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17765     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767  2004.0                  Fidel Castro: American Experience
17767     17768  2000.0                                              Epoch
17768     17769  2003.0                                        The Company
17769     17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [ ]:
!pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit_surprise-1.1.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (15 kB)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (2.0.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.16.3)
Downloading scikit_surprise-1.1.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 31.3 MB/s eta 0:00:00
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.5

In [ ]:
from surprise import Reader,Dataset,SVD
from surprise.model_selection import cross_validate


#Reader ---tells surprise how to read your dataset
#dataset ----> puts your data into surprise's box
          # ---->It converts CSV/DF into something surprise understands.
#SVD - tool

In [ ]:
reader = Reader()

In [ ]:
data=Dataset.load_from_df(df[['Movie_Id','Cust_ID','Ratings']][:100000],reader)
#We are converting a pandas DF into surprise's internal format so SVd can learn from it.

In [ ]:
data

In [ ]:
model=SVD()

In [ ]:
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([1.02474921, 1.02049865, 1.01460023]),
 'fit_time': (1.5159199237823486, 1.2450640201568604, 1.2547364234924316),
 'test_time': (0.14902687072753906, 0.15594768524169922, 0.3838467597961426)}

In [ ]:
# 1331154	---cust_id
user_1331154=df[df['Cust_ID']==1331154]
user_1331154

          Cust_ID  Ratings  Movie_Id
697       1331154      4.0         3
5178      1331154      4.0         8
31460     1331154      3.0        18
92840     1331154      4.0        30
224761    1331154      3.0        44
...           ...      ...       ...
23439584  1331154      4.0      4389
23546489  1331154      2.0      4402
23649431  1331154      4.0      4432
23844441  1331154      3.0      4472
23985561  1331154      4.0      4488

[253 rows x 3 columns]

In [ ]:
#Now lets see how our model will recommend movies to this user

In [ ]:
dummy_title=movie_title.copy()
dummy_title

       Movie_ID    Year                                               Name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17765     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767  2004.0                  Fidel Castro: American Experience
17767     17768  2000.0                                              Epoch
17768     17769  2003.0                                        The Company
17769     17770  2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [ ]:
#In DT1 we have dropped some data --> we will do the same here
drop_movie_index

Index([1598, 1647, 1733, 4099, 1616, 1446,  263,  160, 4259,  322,
       ...
       1858, 4035, 3693, 2805,  820, 4294,  915, 3656, 4338, 4362],
      dtype='int64', name='Movie_Id', length=2699)

In [ ]:
dummy_title=dummy_title[~dummy_title['Movie_ID'].isin(drop_movie_index)]
dummy_title

       Movie_ID    Year                                               Name
2             3  1997.0                                          Character
4             5  2004.0                           The Rise and Fall of ECW
5             6  1997.0                                               Sick
7             8  2004.0                         What the #$*! Do We Know!?
15           16  1996.0                                          Screamers
...         ...     ...                                                ...
17765     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767  2004.0                  Fidel Castro: American Experience
17767     17768  2000.0                                              Epoch
17768     17769  2003.0                                        The Company
17769     17770  2003.0                                       Alien Hunter

[15071 rows x 3 columns]

In [56]:
est_rating=[]
for movie in dummy_title['Movie_ID']:
  rating=model.predict(1331154,movie).est
  est_rating.append(rating)





dummy_title['Rating']=est_rating

In [57]:
dummy_title

,Movie_ID,Year,Name,Rating
17450,17451,2000.0,Along for the Ride,3.842435
15673,15674,1999.0,Arlington Road,3.837226
13510,13511,1993.0,Much Ado About Nothing,3.829831
6459,6460,2005.0,The Game: The Documentary: The DVD,3.822015
10942,10943,2001.0,Ben Folds Five: Complete Sessions at West 54th,3.812657
...,...,...,...,...
15795,15796,1968.0,The One and Only,3.324669
6177,6178,2001.0,Underwaterworld Trilogy: Deep Encouters / Ocea...,3.321500
3320,3321,1999.0,In Dreams,3.304046
10611,10612,1960.0,Swiss Family Robinson,3.260199
8120,8121,1999.0,Search for the Great Sharks: IMAX,3.163974

In [58]:
dummy_title=dummy_title.sort_values('Rating',ascending=False)
dummy_title.head(5)

,Movie_ID,Year,Name,Rating
17450,17451,2000.0,Along for the Ride,3.842435
15673,15674,1999.0,Arlington Road,3.837226
13510,13511,1993.0,Much Ado About Nothing,3.829831
6459,6460,2005.0,The Game: The Documentary: The DVD,3.822015
10942,10943,2001.0,Ben Folds Five: Complete Sessions at West 54th,3.812657